apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-fleet-iac-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-2025/kcc-dash-dont-delete
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
