apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-2025-gemma4-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-2025/gemma4-inference
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-2025-kcc-dash-dont-delete
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-2025/kcc-dash-dont-delete
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-2025-krmapihost-kcc-instance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-2025/krmapihost-kcc-instance
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-gke-a2-highgpu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/gke-a2-highgpu
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-gke-a2-ultra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/gke-a2-ultra
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-gke-a3-mega
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/gke-a3-mega
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-gke-cursor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/gke-cursor
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-kcc-management-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/kcc-management-cluster
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-simple-app-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/simple-app-cluster
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-dataproc-billing-test-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/dataproc-billing-test-cluster
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-containercluster-6lgctkbp5dciv7y
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/containercluster-6lgctkbp5dciv7y
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gca-gke-test-gke-tpuv6-dws
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fkc1e100/gke-fleet-iac.git"
    targetRevision: HEAD
    path: clusters/gca-gke-test/gke-tpuv6-dws
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
